language: ruby
rvm:
  - 2.4
cache: bundler
script: ./scripts/build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: build
  on: turtle-master
  verbose: true

before_install:
  - git clone https://github.com/turtlecoin/turtlecoin-docs.git turtlecoin-docs

env:
  global:
    secure: DwrdiusW+pOgzGk3ENPuxUi+N6wN1z8hwwfL0ZaRkfgfQ0DD5y7N5SbYUZsGFX+T2H138jE4dyIIIBtmfkNN754xSQKR4h/Z7SYKu1Ooyl1e7Vzv0LCG2OAx/cFzbIhKphdAYPtjX9tl49uYbisB4tfjJS4xGE3qGUpUe9UvgDQVVgBvujBpMbUlrmYFIa7+hFD3yONge557U3mD5bTtyerYCjEGpW1C6GVi78CRNIvsj43hpcF/AzyeVTqmOsDpAnQvgrnBDGXUblfWb1yo/Cm40eqnFnoaaJMyn0z2OMBo26ozchlnUXWIxQvI7kRxU3305RIir0VkF20MGQIT+LeTQj8DA4lOEgHdDuuTDXfDwtAF8nGsk7+9y9cmXRW3hZpOFw8CJtsntz9NGo8svyMQypTEh4tIbm+tuUrKzh2Ilt3L0LQ3v1+YjDt3prHNdfibUBMPtEMPKc1DYG41Ub3gtU6iMlyfoMuK/8upF6vj1t76VOx9+zGOtD8MXKyJQzC2oZw/okVzfGCzlmJ0i4TYr7tS7zhi+0BpZ9QvxQVPzdGbauOkwa0tXghuGw6pquVuCVUP07iz6XTuKvgmSVG0GwARd3QY9dV0TqfMMtHNTQS8rd1/jsf1hgE3LFcGfOKhv9VSjDCSckU1hnMmnkOpLyiKogftoejicjpGXv8=
